project_id = "xzwbjwydzzlbqwpsnkew"

[functions.analyze-email]
verify_jwt = false

[functions.sync-gmail]
verify_jwt = true

[functions.connect-gmail]
verify_jwt = true

[functions.get-gmail-auth-url]
verify_jwt = true
